""" This code is entirely generated by AI."""

import turtle
import random
import os
import time

# ------------------ CONSTANTS ------------------
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
FINISH_LINE = 300
SAVE_FILE = "money.txt"
HIGHSCORE_FILE = "highscore.txt"
STARTING_MONEY = 100

TURTLE_DATA = [
    ("Flash", "red"),
    ("Bolt", "blue"),
    ("Rocket", "green"),
    ("Dash", "yellow"),
    ("Shadow", "purple"),
    ("Blaze", "orange"),
    ("Storm", "black"),
    ("Comet", "cyan"),
    ("Viper", "brown"),
    ("Ghost", "pink"),
]

# ------------------ MONEY SAVE / LOAD ------------------
def load_money():
    if os.path.exists(SAVE_FILE):
        with open(SAVE_FILE, "r") as f:
            return int(f.read())
    return STARTING_MONEY

def save_money(amount):
    with open(SAVE_FILE, "w") as f:
        f.write(str(amount))

def load_highscore():
    if os.path.exists(HIGHSCORE_FILE):
        with open(HIGHSCORE_FILE, "r") as f:
            return int(f.read())
    return 0

def save_highscore(score):
    current = load_highscore()
    if score > current:
        with open(HIGHSCORE_FILE, "w") as f:
            f.write(str(score))
        return True
    return False

# ------------------ INPUT FUNCTIONS ------------------
def get_number_of_racers():
    while True:
        n = input("How many turtles racing? (2–10): ")
        if n.isdigit() and 2 <= int(n) <= 10:
            return int(n)
        print("Invalid number.")

def get_bet_amount(balance):
    while True:
        bet = input(f"Balance ${balance}. Enter bet amount (or 'max' for all-in): ")
        if bet.lower() == "max":
            return balance
        if bet.isdigit() and 1 <= int(bet) <= balance:
            return int(bet)
        print("Invalid bet.")

def calculate_multiplier(num):
    return round(1 + (num - 2) * 0.5, 2)

def choose_difficulty():
    difficulties = {
        "easy": {"speed_range": (1, 5), "multiplier": 1.5},
        "medium": {"speed_range": (1, 8), "multiplier": 2.0},
        "hard": {"speed_range": (1, 12), "multiplier": 3.0}
    }
    
    print("\n🎮 Select difficulty:")
    for i, diff in enumerate(difficulties.keys()):
        print(f"  {i+1}. {diff.capitalize()}")
    
    while True:
        choice = input("Enter choice (1-3): ")
        if choice in ["1", "2", "3"]:
            diff = list(difficulties.keys())[int(choice)-1]
            return difficulties[diff]
        print("Invalid choice.")

# ------------------ VISUAL EFFECTS ------------------
def draw_celebration():
    screen.tracer(0)
    firework = turtle.Turtle()
    firework.hideturtle()
    firework.penup()
    
    colors = ["red", "yellow", "blue", "green", "purple", "orange", "cyan", "pink"]
    
    for _ in range(8):
        x = random.randint(-200, 200)
        y = random.randint(-100, 100)
        color = random.choice(colors)
        
        firework.goto(x, y)
        firework.color(color)
        
        for size in range(1, 12):
            firework.dot(size * 3)
            screen.update()
            time.sleep(0.02)
            firework.clear()
    
    firework.clear()
    screen.tracer(1)

def draw_confetti():
    screen.tracer(0)
    confetti = turtle.Turtle()
    confetti.hideturtle()
    confetti.penup()
    
    colors = ["red", "yellow", "blue", "green", "purple", "orange", "cyan", "pink"]
    
    for _ in range(30):
        x = random.randint(-300, 300)
        y = random.randint(-200, 200)
        color = random.choice(colors)
        shape = random.choice(["circle", "square", "triangle"])
        
        confetti.goto(x, y)
        confetti.color(color)
        
        if shape == "circle":
            confetti.dot(10)
        elif shape == "square":
            confetti.begin_fill()
            for _ in range(4):
                confetti.forward(10)
                confetti.right(90)
            confetti.end_fill()
    
    screen.update()
    time.sleep(1.5)
    confetti.clear()
    screen.tracer(1)

# ------------------ UI FUNCTIONS ------------------
def show_instructions():
    screen.bgcolor("darkgreen")
    welcome = turtle.Turtle()
    welcome.hideturtle()
    welcome.penup()
    welcome.color("gold")
    welcome.goto(0, 200)
    welcome.write("🐢 Turtle Racing Casino 🪙", 
                  align="center", font=("Arial", 28, "bold"))
    
    welcome.color("white")
    instructions = [
        "🏁 HOW TO PLAY 🏁",
        "",
        "1. Choose number of turtles (2-10)",
        "2. Select difficulty level",
        "3. Place your bet",
        "4. Pick a turtle to win",
        "5. Watch the race!",
        "",
        "💰 PAYOUT SYSTEM 💰",
        "• More turtles = Higher payout!",
        "• Harder difficulty = Bigger rewards!",
        "",
        f"🎯 Starting balance: ${STARTING_MONEY}",
        "",
        "Press ENTER to start your racing adventure!"
    ]
    
    y_pos = 140
    for line in instructions:
        welcome.goto(0, y_pos)
        welcome.write(line, align="center", font=("Arial", 12, "normal"))
        y_pos -= 25
    
    input("\nPress Enter to continue...")
    welcome.clear()

def game_over_screen(final_balance):
    screen.bgcolor("black")
    game_over = turtle.Turtle()
    game_over.hideturtle()
    game_over.penup()
    game_over.color("red")
    game_over.goto(0, 100)
    game_over.write("GAME OVER", align="center", font=("Arial", 40, "bold"))
    
    game_over.color("gold")
    game_over.goto(0, 30)
    game_over.write(f"Final Balance: ${final_balance}", 
                    align="center", font=("Arial", 24, "bold"))
    
    highscore = load_highscore()
    game_over.goto(0, -30)
    game_over.write(f"High Score: ${highscore}", 
                    align="center", font=("Arial", 20, "bold"))
    
    game_over.color("white")
    game_over.goto(0, -100)
    game_over.write("Thanks for playing! 🐢", 
                    align="center", font=("Arial", 16, "normal"))
    
    time.sleep(5)
    game_over.clear()

def choose_turtle_ui(names):
    screen.tracer(0)
    chooser = turtle.Turtle()
    chooser.hideturtle()
    chooser.penup()
    
    # Display turtle options with colors
    y_pos = 100
    for i, name in enumerate(names):
        chooser.goto(-150, y_pos)
        color = TURTLE_DATA[i][1]
        chooser.color(color)
        chooser.write(f"{i+1}. {name}", font=("Arial", 14, "bold"))
        y_pos -= 40
    
    # Draw sample turtles
    y_pos = 100
    sample_turtles = []
    for i in range(len(names)):
        t = turtle.Turtle(shape="turtle")
        t.hideturtle()
        t.penup()
        t.color(TURTLE_DATA[i][1])
        t.goto(0, y_pos - 10)
        t.showturtle()
        sample_turtles.append(t)
        y_pos -= 40
    
    screen.tracer(1)
    
    while True:
        choice = screen.textinput("Choose Your Champion", 
                                 f"Enter turtle number (1-{len(names)}):")
        if choice and choice.isdigit() and 1 <= int(choice) <= len(names):
            chosen_name = names[int(choice)-1]
            
            # Highlight chosen turtle
            screen.tracer(0)
            chooser.goto(-150, 100 - (int(choice)-1)*40)
            chooser.color("gold")
            chooser.write(f"➤ {chosen_name}", font=("Arial", 14, "bold"))
            screen.tracer(1)
            time.sleep(1)
            
            # Clean up
            for t in sample_turtles:
                t.hideturtle()
            chooser.clear()
            return chosen_name
        print("Invalid choice. Please try again.")

# ------------------ RACE FUNCTIONS ------------------
def setup_race_track():
    screen.clear()
    screen.bgcolor("darkgreen")
    
    # Draw finish line
    line = turtle.Turtle()
    line.hideturtle()
    line.penup()
    line.goto(FINISH_LINE, -250)
    line.setheading(90)
    line.pendown()
    line.color("white")
    line.pensize(3)
    line.forward(500)
    
    # Draw starting line
    line.penup()
    line.goto(-350, -250)
    line.setheading(90)
    line.pendown()
    line.forward(500)
    
    # Draw track lanes
    line.penup()
    for i in range(6):
        y = -250 + i * 100
        line.goto(-350, y)
        line.setheading(0)
        line.pendown()
        line.color("white")
        line.pensize(1)
        line.forward(650)
        line.penup()

def run_race(num_racers, difficulty):
    turtles = []
    y_start = -((num_racers - 1) * 40) / 2
    
    # Create turtles
    for i in range(num_racers):
        name, color = TURTLE_DATA[i]
        t = turtle.Turtle(shape="turtle")
        t.color(color)
        t.penup()
        t.goto(-350, y_start + i * 40)
        t.speed(0)
        t.name = name
        turtles.append(t)
    
    # Race loop
    winner = None
    racing = True
    
    while racing:
        for t in turtles:
            t.forward(random.randint(*difficulty["speed_range"]))
            if t.xcor() >= FINISH_LINE:
                winner = t
                racing = False
                break
    
    return turtles, winner

def replay_race(turtles, difficulty):
    # Reset turtles to start
    y_start = -((len(turtles) - 1) * 40) / 2
    for i, t in enumerate(turtles):
        t.goto(-350, y_start + i * 40)
    
    # Race again with same setup
    winner = None
    racing = True
    
    while racing:
        for t in turtles:
            t.forward(random.randint(*difficulty["speed_range"]))
            if t.xcor() >= FINISH_LINE:
                winner = t
                racing = False
                break
    return winner

# ------------------ MAIN GAME ------------------
def main_game_loop():
    # Initialize screen
    global screen
    screen = turtle.Screen()
    screen.setup(SCREEN_WIDTH, SCREEN_HEIGHT)
    screen.title("🐢 Turtle Racing Casino 🪙")
    
    # Show instructions
    show_instructions()
    
    # Load game data
    money = load_money()
    highscore = load_highscore()
    
    # Create UI turtles
    money_writer = turtle.Turtle()
    money_writer.hideturtle()
    money_writer.penup()
    money_writer.color("gold")
    money_writer.goto(-380, 260)
    
    status_writer = turtle.Turtle()
    status_writer.hideturtle()
    status_writer.penup()
    status_writer.color("white")
    status_writer.goto(0, -260)
    
    # Main game loop
    while money > 0:
        screen.tracer(0)
        setup_race_track()
        
        # Display current stats
        money_writer.clear()
        money_writer.write(f"💰 Money: ${money} | 🏆 High Score: ${highscore}", 
                          font=("Arial", 14, "bold"))
        
        # Low balance warning
        if money < 20:
            warning = turtle.Turtle()
            warning.hideturtle()
            warning.penup()
            warning.color("orange")
            warning.goto(0, 230)
            warning.write("⚠️ Low balance! Consider smaller bets.", 
                         align="center", font=("Arial", 12, "bold"))
            time.sleep(1.5)
            warning.clear()
        
        screen.tracer(1)
        
        print(f"\n{'='*50}")
        print(f"💰 Current Balance: ${money}")
        print(f"🏆 High Score: ${highscore}")
        print(f"{'='*50}")
        
        # Get game parameters
        num_racers = get_number_of_racers()
        difficulty = choose_difficulty()
        multiplier = calculate_multiplier(num_racers) * difficulty["multiplier"]
        
        print(f"\n🐢 Turtles racing: {num_racers}")
        print(f"🎮 Difficulty: {list(difficulty.keys())[0]}")
        print(f"💰 Payout multiplier: x{multiplier:.2f}")
        
        bet_amount = get_bet_amount(money)
        names = [TURTLE_DATA[i][0] for i in range(num_racers)]
        
        # Place bet
        bet_name = choose_turtle_ui(names)
        
        # Run the race
        print("\n🏁 AND THEY'RE OFF! 🏁")
        turtles, winner = run_race(num_racers, difficulty)
        
        # Display results
        screen.tracer(0)
        status_writer.clear()
        
        if winner.name == bet_name:
            winnings = int(bet_amount * multiplier)
            money += winnings
            
            # Check for high score
            if money > highscore:
                if save_highscore(money):
                    highscore = money
                    print("\n🎖️ NEW HIGH SCORE! 🎖️")
                    draw_confetti()
            
            status_writer.color("gold")
            status_writer.write(
                f"🎉 {winner.name} WINS! You earned ${winnings}",
                align="center",
                font=("Arial", 16, "bold")
            )
            
            if winnings > bet_amount * 2:  # Big win celebration
                draw_celebration()
            
            print(f"\n🎉 You won ${winnings}!")
        else:
            money -= bet_amount
            status_writer.color("red")
            status_writer.write(
                f"❌ {winner.name} WINS! You lost ${bet_amount}",
                align="center",
                font=("Arial", 16, "bold")
            )
            print(f"\n❌ You lost ${bet_amount}")
        
        screen.tracer(1)
        save_money(money)
        
        print(f"💰 New balance: ${money}")
        
        # Clean up turtles
        for t in turtles:
            t.hideturtle()
        
        # Ask for replay option
        if money > 0:
            replay = screen.textinput("Continue?", 
                                     "Race again? (y/n)\nReplay same race? (r)")
            
            if replay and replay.lower() == 'r':
                # Replay same race
                turtles, winner = run_race(num_racers, difficulty)
                continue
            elif not replay or replay.lower() != 'y':
                break
    
    # Game over
    if money <= 0:
        print("\n💸 You're out of money! Game Over.")
        game_over_screen(money)
    
    screen.exitonclick()

# ------------------ START GAME ------------------
if __name__ == "__main__":
    print("🎰 Welcome to Turtle Racing Casino! 🎰")
    main_game_loop()
    print("\nThanks for playing Turtle Racing Casino! 🐢🪙")